---

- name: Download Mono repository GPG key
  command: wget -q -O /root/xamarin.gpg http://download.mono-project.com/repo/xamarin.gpg creates=/root/xamarin.gpg

- name: Add Mono repository GPG key
  command: apt-key add /root/xamarin.gpg

- name: Add Mono repository to apt sources
  template: src=templates/judgehost/apt-sources-mono-xamarin.list dest=/etc/apt/sources.list.d/mono-xamarin.list

- name: Install required packages
  apt: pkg={{item}} state=installed update_cache=yes
  with_items:
    - libboost-all-dev
    - libgmp3-dev
    - gcc
    - g++
    - openjdk-7-jre-headless
    - openjdk-7-jdk
    - mono-complete

- name: Creating domjudge-run user
  user: name=domjudge-run group=nogroup shell=/bin/false home=/nonexistent

- name: Configure DOMjudge
  command: chdir={{domjudge_folder}}/domjudge-{{domjudge_version}} ./configure --prefix={{domjudge_folder}}
  sudo_user: domjudge

- name: Build judgehost
  command: chdir={{domjudge_folder}}/domjudge-{{domjudge_version}} make judgehost
  sudo_user: domjudge

- name: Install judgehost
  command: chdir={{domjudge_folder}}/domjudge-{{domjudge_version}} make install-judgehost

- name: Copy sudoers file for judgedaemon
  command: cp /opt/domjudge/judgehost/etc/sudoers-domjudge /etc/sudoers.d

- name: Copy patch for judgedaemon code to judge only submissions from matching team (one judgehost per team)
  template: src=templates/judgehost/judgedaemon.main.php.patch dest=/opt/domjudge/judgehost/lib/judge/judgedaemon.main.php.patch

- name: Apply patch for judgedaemon code to judge only submissions from matching team (one judgehost per team)
  command: chdir=/opt/domjudge/judgehost/lib/judge patch -p0 judgedaemon.main.php judgedaemon.main.php.patch

- name: Copy judgehost config that disables CHROOT
  template: src=templates/judgehost/judgehost-config.php dest=/opt/domjudge/judgehost/etc/judgehost-config.php

- name: Copy restapi.secret for judgedaemon
  template: src=templates/judgehost/restapi.secret dest=/opt/domjudge/judgehost/etc/restapi.secret

- name: Copy judgehost Upstart script
  template: src=templates/judgehost/judgehost.upstart.conf dest=/etc/init/judgehost.conf

- name: Reload Upstart configuration
  command: initctl reload-configuration

- name: Start judgehost daemon
  service: name=judgehost state=started

